version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgresdb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ddd_boilerplate         # Nombre de la base de datos
      POSTGRES_USER: admin                 # Usuario (puedes cambiarlo)
      POSTGRES_PASSWORD: admin123          # Contraseña (asegúrate de cambiarla en producción)
    volumes:
      - ./data:/var/lib/postgresql/data    # Persistencia de datos
