version: '3.8'

services:
  postgres:
    image: docker.io/ankane/pgvector:latest  # PostgreSQL with pgvector extension
    container_name: postgresdb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: climb_zone         # Database name
      POSTGRES_USER: admin                 # User (you can change it)
      POSTGRES_PASSWORD: admin123          # Password (make sure to change in production)
    volumes:
      - ./data:/var/lib/postgresql/data    # Data persistence
      - ./init-pgvector.sql:/docker-entrypoint-initdb.d/init.sql  # pgvector initialization

  redis:
    image: docker.io/library/redis:7-alpine
    container_name: redisdb
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
    command: redis-server --appendonly yes
