import { EmbeddingVector } from '../value-objects/embedding-vector.vo'
import { ZoneMetadata } from '../value-objects/zone-metadata.vo'

/**
 * Zone Embedding Entity
 * Represents a semantic embedding for a climbing zone (crag/sector/area)
 * Combines dense vector embeddings with structured metadata for hybrid search
 */
export class ZoneEmbeddingEntity {
  constructor(
    public readonly id: string,
    public readonly zoneId: string,
    public readonly zoneType: 'crag' | 'sector' | 'area',
    public readonly embedding: EmbeddingVector,
    public readonly textRepresentation: string,
    public readonly metadata: ZoneMetadata,
    public readonly createdAt: Date = new Date(),
    public readonly updatedAt: Date = new Date(),
  ) {}

  /**
   * Create a new zone embedding
   */
  static create(
    zoneId: string,
    zoneType: 'crag' | 'sector' | 'area',
    embedding: number[],
    textRepresentation: string,
    metadata: ZoneMetadata,
  ): ZoneEmbeddingEntity {
    return new ZoneEmbeddingEntity(
      '', // ID will be generated by repository
      zoneId,
      zoneType,
      EmbeddingVector.create(embedding),
      textRepresentation,
      metadata,
    )
  }

  /**
   * Calculate similarity with a query embedding
   */
  calculateSimilarity(queryEmbedding: EmbeddingVector): number {
    return this.embedding.cosineSimilarity(queryEmbedding)
  }

  /**
   * Check if zone matches month filter
   */
  matchesMonth(month: number): boolean {
    return this.metadata.isGoodForMonth(month)
  }

  /**
   * Check if zone matches grade range
   */
  matchesGradeRange(minIndex: number, maxIndex: number): boolean {
    return this.metadata.hasGradeInRange(minIndex, maxIndex)
  }

  /**
   * Get preview text (first 200 characters)
   */
  getPreview(): string {
    return this.textRepresentation.substring(0, 200)
  }

  toJSON(): Record<string, unknown> {
    return {
      id: this.id,
      zoneId: this.zoneId,
      zoneType: this.zoneType,
      textRepresentation: this.textRepresentation,
      metadata: this.metadata.toJSON(),
      createdAt: this.createdAt,
      updatedAt: this.updatedAt,
    }
  }
}
