export { autoLogger, createAutoLogger } from './src/auto-logger'
export { ColorManager } from './src/color-themes'
export * from './src/default-loggers'
export { Logger } from './src/logger'
export type { ExtensibleLogger } from './src/logger.interface'
export type { LoggerConfig } from './src/logger-config.interface'
