/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/favorites` | `/favorites`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/zones` | `/zones`; params?: Router.UnknownInputParams; } | { pathname: `/crag/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/crag/info/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/crag/weather/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/crag/filters/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/sector/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/zone/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/favorites` | `/favorites`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/zones` | `/zones`; params?: Router.UnknownOutputParams; } | { pathname: `/crag/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/crag/info/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/crag/weather/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/crag/filters/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/sector/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/zone/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/favorites${`?${string}` | `#${string}` | ''}` | `/favorites${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/settings${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/zones${`?${string}` | `#${string}` | ''}` | `/zones${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/favorites` | `/favorites`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/zones` | `/zones`; params?: Router.UnknownInputParams; } | `/crag/${Router.SingleRoutePart<T>}` | `/crag/info/${Router.SingleRoutePart<T>}` | `/crag/weather/${Router.SingleRoutePart<T>}` | `/crag/filters/${Router.SingleRoutePart<T>}` | `/sector/${Router.SingleRoutePart<T>}` | `/zone/${Router.SingleRoutePart<T>}` | { pathname: `/crag/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/crag/info/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/crag/weather/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/crag/filters/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/sector/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/zone/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
